if (process.client) {
  import("../static/js/tilda-scripts");
  import("../static/js/lazyload-1.3.min.export");
  import("../static/js/jquery-1.10.2.min");
  import("../static/js/tilda-fallback-1.0.min");
  import("../static/js/tilda-animation-2.0.min");
  import("../static/js/tilda-animation-ext-1.0.min");
  import("../static/js/tilda-blocks-page56709929.min");
  import("../static/js/tilda-events-1.0.min");
  import("../static/js/tilda-forms-1.0.min");
  import("../static/js/tilda-polyfill-1.0.min");
  import("../static/js/tilda-popup-1.0.min");
  import("../static/js/tilda-scripts-3.0.min");
  import("../static/js/tilda-zero-1.1.min");
  import("../static/js/tilda-zero-fixed-1.0.min");
  import("../static/js/tilda-zero-forms-1.0.min");
  import("../static/js/tilda-zero-scale-1.0.min");
  import("../static/js/index");
}
